/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Hamburger(props) {
    
    const hamburguerRef = useRef(null)
    const hamburguer = useGLTF("/static/hamburger.glb");

    return (
        <primitive 
            object={hamburguer.scene}
            ref={hamburguerRef}
            {...props} 
            dispose={null} 
            onClick={(e)=>{
                console.log(e.object.name)
                e.stopPropagation()
    
            }}
        />
        
    );
}

useGLTF.preload("/static/hamburger.glb");